trigger:
- main

variables:
  buildConfiguration: Release
  revision: ci

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: BuildJob
      steps:        
      - task: DotNetCoreCLI@2
        displayName: Dotnet Tool Restore
        inputs:
          command: custom
          custom: tool
          arguments: restore

      - task: Cake@2
        displayName: Cake Build Process
        inputs:
          script: build.cake          
          target: Default
          verbosity: Verbose
          arguments: |
            --configuration $(buildConfiguration) 
            --build $(Build.BuildId) 
            --revision $(revision)

      - task: PublishTestResults@2
        displayName: Publish Tests Results
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '**/*.trx'
          searchFolder: $(Build.SourcesDirectory)/testresults
          testRunTitle: $(Build.BuildNumber)
          publishRunAttachments: true
        condition: always()

      - task: PublishCodeCoverageResults@1
        displayName: Publish Code Coverage Results
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: $(Build.SourcesDirectory)/testresults/**/coverage.cobertura.xml
          reportDirectory: $(Build.ArtifactStagingDirectory)
        condition: always()

      - task: CopyFiles@2
        displayName: Copy Files to ArtifactStagingDirectory
        inputs:
          SourceFolder: $(Build.SourcesDirectory)/artifacts
          Contents: |
            *.zip
            *.nupkg
          TargetFolder: $(Build.ArtifactStagingDirectory)
          CleanTargetFolder: true

      - task: PublishBuildArtifacts@1
        displayName: Publish Artifacts
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: drop
          publishLocation: Container

  - stage: DeployPackage
    displayName: Deployment of the nuget package
    condition: |
      and
      (
        succeeded('Build'),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
    - job: DeployPackage
      steps:
        - download: current
          displayName: 'Download the artifacts'
          artifact: 'drop'

        - task: DotNetCoreCLI@2
          displayName: Publishing the nuget Package to the Azure DevOps feed
          inputs:
            command: 'push'
            packagesToPush: '$(Pipeline.Workspace)/drop/**/*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: 'afa87726-6977-4997-b7df-99c5d3cf444e/fb789773-b199-461c-a975-0f88275a8f1f'

  - stage: DeployWebApp
    displayName: Deployment of the web application
    condition: |
      and
      (
        succeeded('Build'),
        eq(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
    - job: DeployWebApp
      steps:
        - download: current
          displayName: 'Download the artifacts'
          artifact: 'drop'

        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Yannick WILLI – MPN(0a5e66fb-a6b6-4a7e-b419-3f7e47ae620c)'
            appType: 'webAppLinux'
            WebAppName: 'democake-ywi-devops'
            packageForLinux: '$(Pipeline.Workspace)/drop/**website.zip'