trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Dotnet Tool Restore
  inputs:
    command: custom
    custom: tool
    arguments: restore

- task: Cake@2
  displayName: Cake Build Process
  inputs:
    script: 'build.cake'
    target: 'Default'
    verbosity: 'Verbose'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\artifacts'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'