trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Dotnet Tool Restore
  inputs:
    command: custom
    custom: tool
    arguments: restore

- task: Cake@2
  displayName: Cake Build Process
  inputs:
    script: 'build.cake'
    target: 'Default'
    verbosity: 'Verbose'